### ISSUE TITLE
[BREAKING] "Select all" twice in the search box also selects all content in the current page

### ISSUE THREAD

**Issue by dalmo3** [Roam-Research/issues#79] opened 2020-05-02 12:26 UTC
**Describe the bug**

While typing in the search box, doing 'Select All' (Ctrl-A on Windows) twice will also select  all content in the current page. 

That means if you press backspace or del, all's gone. 

I had to rely on Undo/Ctrl-Z to get the data back. Luckily it worked, but what if I had navigated somewhere else.

Doesn't affect the Daily notes, nor the sidebar, nor the linked/unlinked references area.

**To Reproduce**

1. Type something in the search box
2. Ctrl-A twice

OR

1. Click on search bar
2. Ctrl-A

What happens now is weird, you can still type in the box, but any other key triggers actions in the document:

- pressing del or backspace will delete all the content
- pressing enter will place the cursor at the first line
- pressing arrow keys will make you navigate through the doc

I.e. the regular actions you'd expect if you do a Select All on the doc itself.

**GIF demonstrating** https://share.getcloudapp.com/7Ku0EkWq

**System Information:**
Brave Win10

**Comment by GitMurf** [comment] 2020-05-02 18:00
@dalmo3 no need to add [BREAKING] in your issue title as if yours is any more important than everyone else’s. To me this isn’t even a bug. Why would you be pressing Carl + A twice anyways? And if you did, that is doing what it should... selecting all on the page. If you then delete, then what would you expect. I’m sorry but I don’t see this as a bug even. But even if it is, please don’t flag with your title like yours is so important compared to others. Thanks.

**Comment by dalmo3** [comment] 2020-05-03 15:28
Being that aggressive I assume you're not part of Roam Research. But just in case you are, I will answer to your points.

1. It's breaking because it can lead to unintended data loss. I never passed judgement on the importance of any other issue, you did.
2. Show me any website where an input field loses focus by doing Select All. If it's _"not even a bug"_, then it's just bad design, let alone _"doing what it should do"_. It shouldn't.
3. Ah, the good old _"why would you do this anyway?"_. Read the post again. The bug also happens if you do it ONLY ONCE when the search box is empty. You can edit the issue title and remove the _twice_ if you wish. But of course you're going to say "_why would anyone do select all in an empty field?"_.  It also happens if there's already some text in there, you click on it and press Ctrl-A ONCE (because clicking on the box auto-selects the text). Who knows how many other ways this bug can or cannot happen. I'm reporting what happened, that's it.

**Comment by GitMurf** [comment] 2020-05-04 04:39
@dalmo3 correct, no affiliation with Roam research. Sorry for blunt/aggressive language I just have been frustrated as of late with the way people are posting to Slack channels and people reporting bugs etc. without any supporting details which makes it impossible for anyone to troubleshoot. You provided very nice details on recreating issue and support/explanation I just didn’t like the BREAKING piece and overreacted. It is just that if everyone did this when they thought their issue was very important then it would just be a mess and no point. We’ve all had some super serious issues that haven’t been resolved for long periods but the Roam team is only a few engineers so it takes time and hence why we aren’t paying for the product yet. 

Anyways, just please in future try not to raise fire alarm with BREAKING type stuff because I don’t want others to start doing it too then and trust me, this likely won’t get “fixed” for a while. Again I actually don’t even know if this is classified as a Bug.

**Comment by everruler** [comment] 2020-05-04 23:10
I can't reproduce this, also on Brave Win10. Multiple Ctrl-A presses works as expected in the search box.

**Comment by filipesilva** [comment] 2020-06-08 14:38
I can reproduce when on a specific page (e.g. not on the daily log). Other keybinds, like ctrl+z, are also spilling over.

**Comment by filipesilva** [comment] 2020-06-09 11:49
Heya, this should be fixed and live in some 20 minutes. Thanks for the report!

**Closed** 2020-06-09 11:49 UTC
Labels: area: keybinds, bug
