### ISSUE TITLE
Randomly disappearing notes

### ISSUE THREAD

**Issue by nkrinsky** [Roam-Research/issues#111] opened 2020-05-06 13:42 UTC
I really enjoy using Roam for note taking, but sometimes I will open a day's notes to find that some notes are partially or fully gone. This is really frustrating as I can't find any pattern as to why and when some comments vanish. It's hard for me to trust the platform if I can't be sure that notes will be saved. This happens to me at least once a day, and the notes that disappear can't be recovered. Is there any way to manually save to ensure that my notes are not lost?

**Comment by nt92** [comment] 2020-05-06 17:24
also running into this issue

**Comment by lolomoo** [comment] 2020-05-07 19:49
have had that issue occur twice today.  bummed because I like the tool but if I am going to lose content that I cannot get back...

**Comment by javieralaves** [comment] 2020-05-08 15:45
Hey Nate, due to the large influx of users while Roam's in beta, there can be syncing issues and this leads to notes being lost. There are stability improvements in the works, but until just to be sure that you don't lose any more notes, I recommend that you export your data every now and then, specially after inputting large amounts of data. Additionally, hovering over the status icon (the colored dot on the top right), you'll get some context on how your sync progresses.

**Comment by ChenMorSays** [comment] 2020-05-08 17:50
Also running into this issue... hits my Roam DB bad.

**Comment by ChenMorSays** [comment] 2020-05-08 17:50
Also running into this issue... hits my Roam DB badly.

**Comment by filipesilva** [comment] 2020-05-14 14:58
Heya, I'm marking this issue as a duplicate of https://github.com/Roam-Research/issues/issues/49 to make it easier to track. I'm adding updates there.

**Closed by filipesilva** 2020-05-14 14:58 UTC
Labels: bug
