### ISSUE TITLE
Problems with right-clicking for context menu in Safari

### ISSUE THREAD

**Issue by Muskatinho** [Roam-Research/issues#169] opened 2020-05-10 22:50 UTC
**Describe the bug**

I was using Roam in Safari and tried to right-click the bullet to get the context menu. All I got was the macOS system context menu (back, reload page, etc.). I tried it in Chrome and it worked. Is this a recent issue or does right-clicking to get the context menu not work in Safari? Also, is there any way to change the keyboard shortcut triggers if the built-in shortcuts conflict with other background programs?

**To Reproduce**

1. Go to bullet point on Safari
2. Click on right-click
3. See bug

**System Information:**
 - Roam version: 0.6.1-fb84ed08
 - Device: iMac Pro
 - OS: Catalina
 - Browser Safari

**Additional context**

**Comment by minimaldesign** [comment] 2020-06-24 23:41
For what it's worth… Same bug in Firefox.

No native app is totally understandable, but support for *only* Chrome [brings this to mind](https://www.theverge.com/2018/1/4/16805216/google-chrome-only-sites-internet-explorer-6-web-standards) 😅 

Super awesome app, but I gotta say that's pretty disappointing…

**Comment by panterarocks49** [comment] 2020-07-15 05:50
I'm not able to reproduce this bug on

Roam version: 0.7.1-7492e2d3
Device: MacBook Pro
OS: Catalina
Browser: Safari/Firefox

Possible we could have accidentally fixed it in the past month, is this still an issue for y'all?
Are you using a mouse or the touchpad?

Also we are planning on moving the context menu into a ... next to the bullet

**Comment by Muskatinho** [comment] 2020-07-15 14:59
Issue is ongoing.

**Comment by minimaldesign** [comment] 2020-07-16 18:07
Still happening for me.

Latest Firefox on Catalina. 2013 macbook pro, using two finger tap setting. Let me know if you need more info... 

The added UI element seems like a good idea though... I'd rather you focus on that instead 😎👍

**Comment by Muskatinho** [comment] 2020-07-16 20:07
Check out this GIF of my experience (attached).
[image: CleanShot 2020-07-15 at 07.55.07.gif]

**Comment by panterarocks49** [comment] 2020-07-17 23:18
Thanks for the responses!
We have an open PR to move the context menu into a UI icon, should be up within a week or so. Will close this when it's deployed.

**Closed** 2020-08-12 02:15 UTC
Labels: area: block context menu, bug
