### ISSUE TITLE
Roam on iPad intermittently creating new pages prematurely when adding a page reference

### ISSUE THREAD

**Issue by mg0716** [Roam-Research/issues#492] opened 2020-08-18 12:29 UTC
Sometimes (not all) when opening a bracket for a page reference, and typing a phrase, a new page will be created prematurely (before completing the block or clicking a page). Even if that whole block is deleted before `Enter` is hit, or it is completed, the page will still be present.

I initially noticed this because I often write my son's name quickly with open brackets, then the lowercase start of his name. Today Roam began to insert it as a page, ahead of the Title case version…which I then noticed that it actually made the new page unexpectedly.

I have confirmed this does not happen on my Mac or elsewhere other than my iPad.

Video is here: https://youtu.be/EP_7cCA-TCM
* 00:08 I type in `[[nash]]`
    * Note that `nash` does not exist as a table in my database yet
* 00:10 Notice that `nash` now shows up above `Nash`
* 00:29 I delete the block without clicking out or hitting `Enter` before
    * At this point, `nash` should still not be a page
* 00:38 I search for `nash` and it does indeed show up as a page

**To Reproduce**

1. Type something after `[[` that doesn't exist in the database
2. Observe that new word being available as a page

Unfortunately, I'm noticing that this problem has been intermittent

**System Information:**
 - Roam version: Unable to determine, as the iPad version does not have the help button
 - Device: iPad 12.9" (2018)
 - OS: iOS 14.0 beta 4
 - Browser: Safari

**Additional context**

**Comment by kylestratis** [comment] 2020-08-18 12:48
This appears to be typical behavior - I've been working around it since I started using Roam on MacOS in both Firefox and Chromium-based browsers. New pages will be created even before closing the double brackets.

**Comment by mg0716** [comment] 2020-08-18 13:12
@kylestratis This is not typical for me. I've used the same steps to reproduce on my mac and have not encountered this issue. If you get a chance, try to reproduce and perhaps record your screen.

**Comment by kylestratis** [comment] 2020-08-18 13:22
@mg0716 I tested this again and it appears that you are correct. This is apparently now fixed - at least for desktop browsers. Which is nice because it was a huge pain. I'll see if I can confirm it on Firefox for iPad to figure out if it's a Safari issue (common) or mobile issue.

**Comment by kylestratis** [comment] 2020-08-18 13:36
Following up, could not reproduce on Firefox on iPad.

**Comment by filipesilva** [comment] 2020-08-19 09:06
First of all, thank you so much for a super detailed issue!

I think this is intended behaviour actually, because:
- we save the current version of what you're typings if you stop typing for a second or so
- referencing a page that does not exist creates the page

You can confirm this because you should see a yellow flash on the sync dot. IIRC these pages then get cleaned up later.

Which I guess now turns the question into "what's different between iPad and desktop". I think iPad is updating the autocomplete checkbox whereas desktop isn't. Not sure why. Might be the cause of reduced performance in some cases even.

**Comment by mg0716** [comment] 2020-08-19 10:21
Thanks @filipesilva! Appreciate you having a look at this.

So I’ll call out that while that might be intended behavior, it’s actually quite problematic. I ran into it again today as I opened brackets typed in `covid`. My goal was to use the brackets to search for the page to get my `[[COVID-19]]` reference.

Therein lies the issue → I’ve always used open brackets as a way of searching. However, now with the behavior this way it’s going to create a lot of unlinked orphans pages.

The logic I would have expected is:
* If brackets are used around a new phrase, wait until Enter is used, or user navigates away from the block

**Comment by matiassingers** [comment] 2020-08-19 10:31
I just noticed a change in behavior today as well after my browser was restarted, it seems like the delay for the suggested page references takes too long to show up which leads to a new page being created before having the ability to select the reference:

![roam-page-reference-behavior](https://user-images.githubusercontent.com/938453/90624056-f474b280-e249-11ea-9ab0-89ad3192a31f.gif)

It also seems somewhat inconsistent (as per gif above), note that I had just done the test using [[roam]] first which created a new page that I then deleted — that could be why it didn't show up when I started recording.


Separately, might not be related at all: all my queries are suddenly broken and not returning any results. I checked my console and noticed this: `Customer cus_[redacted] does not have an active subscription`

**Comment by matiassingers** [comment] 2020-08-20 08:20
I'm not experiencing the issue any longer after updating to `0.7.3-e272efd5`, thanks guys!

**Comment by mg0716** [comment] 2020-08-20 11:27
FYI I’m still experiencing issues on my iPad, and Roam says that it’s up to date with the latest.

**Comment by filipesilva** [comment] 2020-08-20 12:22
@mg0716 iirc the change to the slash command was reverted yesterday. The change to references is still there and will need to be addressed separately. I can confirm that the extraneous new pages will be removed on startup though.

**Comment by filipesilva** [comment] 2020-08-24 08:17
@mg0716 I can't repro on iPad (iPadOS 14 beta 5) either, are you still seeing it?

**Comment by mg0716** [comment] 2020-08-24 11:43
Yes, I can still see it. Was experiencing it today. Happy to dig in deeper and do a screenshare if need be.
re404 <notifications@github.com> wrote:
“@mg0716 I can't repro on iPad (iPadOS 14 beta 5) either, are you still seeing it?”

**Comment by panterarocks49** [comment] 2020-08-25 05:17
I can't reliably reproduce this, but I think I have a fix for it. Could you guys try Roam on this url and let me know if it's fixed there? https://relemma-git-fix-492.roamresearch.now.sh/

**Comment by mg0716** [comment] 2020-08-25 16:50
> Could you guys try Roam on this url and let me know if it's fixed there?

I can confirm that with a little bit of testing, it appears as though the problem was solved with this build. I didn't get super extensive with it, but in comparing the old vs. new I saw consistently how the new code did not reproduce the same effect as the old.

**Comment by panterarocks49** [comment] 2020-08-27 03:56
Awesome, deploying the fix to production now.

**Closed** 2020-08-27 03:56 UTC
Labels: bug, iPad
