### ISSUE TITLE
intermittent data loss starting 4/27/2020

### ISSUE THREAD

**Issue by pmbauer** [Roam-Research/issues#42] opened 2020-04-29 00:19 UTC
**Describe the bug**

observing on 4/27/2020
* stuck on orange dot for 30 minutes at a time
* oddly missing minor edits to blocks after re-visiting a note after some period (added tags, checked todo) even though changes I made to other blocks later than the missing changes were preserved

**To Reproduce**

1. none yet :(

**System Information:**
 - Device: desktop computer
 - OS: MacOS 10.15.4
 - Browser: Firefox 

**Additional context**
I was running with one active instance of Roam.
Stable, fast Internet.
Been using Roam heavily for a few weeks but hadn’t encountered this until 4/27

Anecdotal uptick in data loss reports for in #bug-reports channel and on twitter the past few days

**Comment by filipesilva** [comment] 2020-05-14 14:50
Heya, I'm merging this as a duplicate of https://github.com/Roam-Research/issues/issues/49 just to make it easier to track and five updates.

**Closed by filipesilva** 2020-05-14 14:50 UTC
Labels: bug
