### ISSUE TITLE
Zoom out shortcut broken in Safari on macOS

### ISSUE THREAD

**Issue by mscheibe** [Roam-Research/issues#142] opened 2020-05-09 04:05 UTC
**Describe the bug**

`cmd + ,` -> Opens current app preferences, i.e. Safari Preferences, so cannot zoom out
**To Reproduce**

1. Type `cmd + ,`
2. See Safari Preferences

**System Information:**
 - Roam version: 0.6.1-aacf1e8e
 - Device: Desktop
 - OS: macOS
 - Browser Safari

**Additional context**

**Comment by pratul** [comment] 2020-05-09 20:37
This is a (near) duplicate of #143.

**Comment by Stvad** [comment] 2020-05-09 23:15
yeah, it's not a Safari thing, it's macOS thing as described in #143

**Comment by mscheibe** [comment] 2020-05-09 23:54
Zoom out works in Chrome on macOS.

**Comment by panterarocks49** [comment] 2020-06-09 01:19
Closing in favor of https://github.com/Roam-Research/issues/issues/143

**Closed by panterarocks49** 2020-06-09 01:19 UTC
Labels: area: keybinds, bug
